# Generated by Django 3.2.12 on 2022-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='co2',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='data_ora',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='hum',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='pm25',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='pmio',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='temp',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='voc',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
