# Generated by Django 3.2.12 on 2022-03-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220316_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pm25',
        ),
    ]
