# Generated by Django 3.2.12 on 2022-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_pm25'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pm25',
            field=models.IntegerField(default=None),
        ),
    ]
